from __future__ import annotations

import pytest

from reposcope.ingest import language
from reposcope.ingest.clone import CloneError, parse_url
from reposcope.ingest.filters import ExclusionReason, check_content, check_path
from reposcope.ingest.walk import summarize, walk


# --- URL parsing -------------------------------------------------------------


@pytest.mark.parametrize(
    "url,owner,name",
    [
        ("https://github.com/psf/requests", "psf", "requests"),
        ("https://github.com/psf/requests.git", "psf", "requests"),
        ("github.com/psf/requests/", "psf", "requests"),
        ("https://www.github.com/a-b/c.d_e", "a-b", "c.d_e"),
        ("https://github.com/psf/requests?tab=readme", "psf", "requests"),
    ],
)
def test_parse_url_accepts_real_urls(url, owner, name):
    ref = parse_url(url)
    assert (ref.owner, ref.name) == (owner, name)


@pytest.mark.parametrize(
    "url",
    [
        "file:///etc/passwd",
        "https://gitlab.com/a/b",
        "https://github.com/psf",
        "https://github.com/psf/requests --upload-pack=touch",
        "ssh://git@github.com/a/b",
        "https://evil.com/github.com/a/b",
    ],
)
def test_parse_url_rejects_everything_else(url):
    with pytest.raises(CloneError):
        parse_url(url)


# --- Exclusion ---------------------------------------------------------------


@pytest.mark.parametrize(
    "path,reason",
    [
        ("node_modules/left-pad/index.js", ExclusionReason.VENDORED),
        ("src/vendor/jquery.js", ExclusionReason.VENDORED),
        (".venv/lib/python3.11/site-packages/x.py", ExclusionReason.VENDORED),
        ("package-lock.json", ExclusionReason.LOCKFILE),
        ("backend/poetry.lock", ExclusionReason.LOCKFILE),
        ("assets/logo.png", ExclusionReason.BINARY_EXT),
        ("static/app.min.js", ExclusionReason.MINIFIED),
        ("proto/user_pb2.py", ExclusionReason.GENERATED),
        (".cache/thing.py", ExclusionReason.HIDDEN),
    ],
)
def test_excluded_paths(path, reason):
    decision = check_path(path)
    assert not decision.included
    assert decision.reason is reason


@pytest.mark.parametrize(
    "path",
    [
        "src/main.py",
        "app/routes/users.ts",
        ".github/workflows/ci.yml",
        "Dockerfile",
        "docs/architecture.md",
        "vendors/report.py",  # 'vendors' != 'vendor'
    ],
)
def test_included_paths(path):
    assert check_path(path).included


def test_binary_content_detected_by_nul_byte():
    decision = check_content(b"MZ\x00\x00\x90", 5, 1_000_000)
    assert decision.reason is ExclusionReason.BINARY_CONTENT


def test_generated_header_detected():
    decision = check_content(b"// Code generated by protoc. DO NOT EDIT.\n", 42, 1_000_000)
    assert decision.reason is ExclusionReason.GENERATED


def test_oversized_file_excluded():
    decision = check_content(b"print(1)\n", 2_000_000, 1_000_000)
    assert decision.reason is ExclusionReason.TOO_LARGE


def test_unminified_source_passes():
    body = b"def add(a, b):\n    return a + b\n" * 10
    assert check_content(body, len(body), 1_000_000).included


# --- Language ----------------------------------------------------------------


@pytest.mark.parametrize(
    "path,expected",
    [
        ("a/b.py", "python"),
        ("a/b.tsx", "typescript"),
        ("a/b.mjs", "javascript"),
        ("Dockerfile", "dockerfile"),
        ("Dockerfile.prod", "dockerfile"),
        ("README.md", "markdown"),
        ("mystery.xyz", None),
    ],
)
def test_language_detection(path, expected):
    assert language.detect(path) == expected


def test_shebang_fallback():
    assert language.detect("scripts/deploy", b"#!/usr/bin/env python3\n") == "python"


def test_only_python_and_ts_are_parseable():
    assert language.is_parseable("python")
    assert language.is_parseable("typescript")
    assert not language.is_parseable("go")
    assert not language.is_parseable(None)


# --- Walking -----------------------------------------------------------------


@pytest.fixture
def fake_repo(tmp_path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("import os\n\n\ndef run():\n    return os\n")
    (tmp_path / "src" / "app.ts").write_text("export const x = 1;\n")
    (tmp_path / "node_modules" / "dep").mkdir(parents=True)
    (tmp_path / "node_modules" / "dep" / "index.js").write_text("module.exports = 1;\n")
    (tmp_path / "package-lock.json").write_text("{}\n")
    (tmp_path / "logo.png").write_bytes(b"\x89PNG\r\n\x1a\n\x00\x00")
    (tmp_path / "README.md").write_text("# Hi\n")
    return tmp_path


def test_walk_partitions_the_tree(fake_repo):
    files = list(walk(fake_repo))
    by_path = {f.rel_path: f for f in files}

    assert by_path["src/main.py"].included
    assert by_path["src/main.py"].language == "python"
    assert by_path["src/main.py"].loc == 5
    assert by_path["src/main.py"].content_hash

    assert not by_path["package-lock.json"].included
    assert by_path["logo.png"].exclusion_reason is ExclusionReason.BINARY_EXT


def test_walk_does_not_descend_into_vendored_dirs(fake_repo):
    paths = {f.rel_path for f in walk(fake_repo)}
    assert not any(p.startswith("node_modules/") for p in paths)


def test_walk_ignores_symlinks(fake_repo, tmp_path):
    outside = tmp_path.parent / "outside.py"
    outside.write_text("secret = 1\n")
    (fake_repo / "link.py").symlink_to(outside)
    assert "link.py" not in {f.rel_path for f in walk(fake_repo)}


def test_coverage_summary(fake_repo):
    stats = summarize(list(walk(fake_repo)))
    assert stats["files_parseable"] == 2
    assert stats["included_by_language"]["python"] == 1
    assert stats["excluded_by_reason"]["lockfile"] == 1
