"""Decide which files enter an analysis run.

Excluded files are still recorded in the `files` table with an
`exclusion_reason`, never silently dropped: the counts are part of the
measurement report, and "we skipped 40% of the repo" is something a reader of
the analysis deserves to see.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import PurePosixPath


class ExclusionReason(str, Enum):
    VENDORED = "vendored"
    LOCKFILE = "lockfile"
    BINARY_EXT = "binary_extension"
    BINARY_CONTENT = "binary_content"
    GENERATED = "generated"
    MINIFIED = "minified"
    TOO_LARGE = "too_large"
    UNSUPPORTED = "unsupported_language"
    HIDDEN = "hidden_path"


# Directory names that mean "not this repo's code". Matched on any path segment.
VENDOR_DIRS = frozenset(
    {
        "node_modules", "bower_components", "jspm_packages",
        "vendor", "third_party", "thirdparty", "external", "externals",
        "site-packages", "dist-packages", ".venv", "venv", "env", "virtualenv",
        "dist", "build", "out", "target", ".next", ".nuxt", ".output",
        "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache",
        ".git", ".hg", ".svn", ".tox", ".eggs", "coverage", "htmlcov",
        "Pods", "Carthage", "DerivedData",
    }
)

LOCKFILES = frozenset(
    {
        "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "npm-shrinkwrap.json",
        "bun.lockb", "bun.lock",
        "poetry.lock", "Pipfile.lock", "pdm.lock", "uv.lock", "conda-lock.yml",
        "requirements.txt.lock",
        "Gemfile.lock", "composer.lock", "Cargo.lock", "go.sum", "mix.lock",
        "pubspec.lock", "Package.resolved", "gradle.lockfile",
    }
)

BINARY_EXTS = frozenset(
    {
        # images / media
        ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".webp", ".tiff", ".avif",
        ".mp3", ".mp4", ".wav", ".ogg", ".webm", ".mov", ".avi", ".flac", ".m4a",
        # fonts
        ".woff", ".woff2", ".ttf", ".otf", ".eot",
        # archives
        ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar", ".jar", ".war",
        # compiled / objects
        ".pyc", ".pyo", ".pyd", ".so", ".dylib", ".dll", ".exe", ".o", ".a",
        ".class", ".wasm", ".bin", ".dat", ".db", ".sqlite", ".sqlite3",
        # documents
        ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
        # misc
        ".lock", ".pack", ".idx", ".DS_Store",
    }
)

# Substrings that mark machine-written source.
GENERATED_MARKERS = (
    "_pb2.py", "_pb2_grpc.py", ".pb.go", "_generated.", ".generated.",
    ".g.dart", ".freezed.dart", "__generated__",
)

# Checked against the first ~2 KB of a text file.
GENERATED_HEADERS = (
    b"@generated",
    b"DO NOT EDIT",
    b"do not edit",
    b"Code generated by",
    b"autogenerated",
    b"auto-generated",
)


@dataclass(frozen=True)
class Decision:
    included: bool
    reason: ExclusionReason | None = None


def _segments(rel_path: str) -> tuple[str, ...]:
    return PurePosixPath(rel_path).parts


def check_path(rel_path: str) -> Decision:
    """Path-only checks. Cheap, runs before the file is opened."""
    parts = _segments(rel_path)
    name = parts[-1] if parts else rel_path

    for seg in parts[:-1]:
        if seg in VENDOR_DIRS:
            return Decision(False, ExclusionReason.VENDORED)
        # .github and .vscode carry real config; other dotdirs rarely do.
        if seg.startswith(".") and seg not in {".github", ".vscode", ".circleci"}:
            return Decision(False, ExclusionReason.HIDDEN)

    if name in LOCKFILES:
        return Decision(False, ExclusionReason.LOCKFILE)

    lowered = name.lower()
    suffix = PurePosixPath(lowered).suffix
    if suffix in BINARY_EXTS:
        return Decision(False, ExclusionReason.BINARY_EXT)

    if lowered.endswith((".min.js", ".min.css", ".min.mjs", ".bundle.js", ".chunk.js")):
        return Decision(False, ExclusionReason.MINIFIED)

    if any(m in rel_path for m in GENERATED_MARKERS):
        return Decision(False, ExclusionReason.GENERATED)

    return Decision(True)


def check_content(head: bytes, size_bytes: int, max_file_bytes: int) -> Decision:
    """Content checks on the first chunk of the file."""
    if size_bytes > max_file_bytes:
        return Decision(False, ExclusionReason.TOO_LARGE)

    # A NUL byte in the first chunk is the standard binary heuristic; git uses it.
    if b"\x00" in head:
        return Decision(False, ExclusionReason.BINARY_CONTENT)

    window = head[:2048]
    if any(marker in window for marker in GENERATED_HEADERS):
        return Decision(False, ExclusionReason.GENERATED)

    # Minified source that dodged the filename check: very long mean line length.
    lines = window.split(b"\n")
    if len(lines) > 1 and (len(window) / len(lines)) > 500:
        return Decision(False, ExclusionReason.MINIFIED)

    return Decision(True)
