// SYNTHETIC sample documents and a SIMULATED extractor output for the no-key demo.
// The confidences imitate an overconfident model. None of this is a real model's output.
export const SAMPLES = [
  {
    id: "clean",
    label: "Clean invoice",
    text: "ACME SUPPLIES PVT LTD\nTax Invoice\nInvoice No: INV-2231\nDate: 2026-09-15\nDue date: 2026-10-15\nBill to: Kiran Traders, Pune\nItems: 40 x Steel brackets @ 1,205.00\nTotal amount: ₹48,200.00",
    extracted: [
      { field: "vendor_name", value: "Acme Supplies Pvt Ltd", confidence: 0.99 },
      { field: "invoice_number", value: "INV-2231", confidence: 0.99 },
      { field: "due_date", value: "2026-10-15", confidence: 0.98 },
      { field: "total_amount", value: "48200.00", confidence: 0.99 },
    ],
  },
  {
    id: "messy",
    label: "Messy scan",
    text: "N0rth Star Logistics\nlnvoice # NS-88l9\nlssued 03/09/2026   Payable within 30 days\nFreight Mumbai -> Delhi\nSub total 21,450\nGST 18% 3,861\nT0TAL 25,311",
    extracted: [
      { field: "vendor_name", value: "North Star Logistics", confidence: 0.96 },
      { field: "invoice_number", value: "NS-8819", confidence: 0.93 },
      { field: "due_date", value: "2026-10-03", confidence: 0.91 },
      { field: "total_amount", value: "21450", confidence: 0.97 },
    ],
  },
  {
    id: "missing",
    label: "Missing due date",
    text: "Blue Lotus Design Studio\nInvoice BL-104\nLogo and brand kit\nAmount payable: ₹15,000\nThank you!",
    extracted: [
      { field: "vendor_name", value: "Blue Lotus Design Studio", confidence: 0.98 },
      { field: "invoice_number", value: "BL-104", confidence: 0.97 },
      { field: "due_date", value: null, confidence: 0.6 },
      { field: "total_amount", value: "15000", confidence: 0.95 },
    ],
  },
  {
    id: "resume",
    label: "Resume",
    text: "Priya    Sharma\nPune, India | priya.sharma@example.com | +91 98765 43210\nlinkedin.com/in/priya-sharma-example | github.com/priya-example | priya.example.dev\n\nSummary\nBackend engineer who builds payment and billing APIs with Go, Python and PostgreSQL. Cares about test coverage,\nclear on-call runbooks and small, safe releases.\n\nExperience\nSoftware Engineer                                                                      Jan 2024 – Present\nLotus Payments Pvt Ltd, Bengaluru\n• Built a refund service in Go that handles 40k requests per day with idempotent retries and\n  audit logs.\n• Cut invoice generation time from 9 minutes to 40 seconds by moving PDF rendering to a queue.\nSoftware Engineering Intern                                                            Jun 2023 – Dec 2023\nKiran Cloud Services, Pune\n• Wrote Python scripts to reconcile ledger entries and flagged 1,200 mismatched rows for re-\n  view.\n\nProjects\nLedgerLite – Double-entry Bookkeeping API                                           Go, PostgreSQL\n• REST API with journal entries, trial balance and month-end close, covered by 180 unit tests.\nQueueWatch – Job Queue Dashboard\n• Shows stuck jobs, retry counts and schedul-\n  ing delays for Redis queues.\n\nTechnical Skills\nLanguages: Go, Python, SQL, TypeScript\nTools: PostgreSQL, Redis, Docker, Kubernetes, GitHub Actions, Grafana,\nPrometheus\n\nEducation\nBE in Computer Engineering                                                                 2019 – 2023\nSavitribai Phule Pune University\n",
    extracted: [
      { field: "name", label: "Name", value: "Priya Sharma", confidence: 0.99 },
      { field: "headline", label: "Headline", value: "Backend Engineer", confidence: 0.99 },
      { field: "email", label: "Email", value: "priya.sharma@example.com", confidence: 0.99 },
      { field: "phone", label: "Phone", value: "+91 98765 43210", confidence: 0.98 },
      { field: "location", label: "Location", value: "Pune, India", confidence: 0.97 },
      { field: "linkedin", label: "LinkedIn", value: "linkedin.com/in/priya-sharma-example", confidence: 0.99 },
      { field: "github", label: "GitHub", value: "github.com/priya-example", confidence: 0.98 },
      { field: "website", label: "Website", value: "priya.example.dev", confidence: 0.9 },
      { field: "summary", label: "Summary", value: "Backend engineer who builds payment and billing APIs with Go, Python and PostgreSQL.", confidence: 0.9 },
      { field: "job_1_title", label: "Job 1 title", value: "Software Engineer", confidence: 0.99 },
      { field: "job_1_company", label: "Job 1 company", value: "Lotus Payments Pvt Ltd", confidence: 0.97 },
      { field: "job_1_dates", label: "Job 1 dates", value: "Jan 2024 - Present", confidence: 0.98 },
      { field: "job_1_summary", label: "Job 1 summary", value: "Built a refund service in Go that handles 40k requests per day with idempotent retries and audit logs.", confidence: 0.9 },
      { field: "job_2_title", label: "Job 2 title", value: "Software Engineering Intern", confidence: 0.98 },
      { field: "job_2_company", label: "Job 2 company", value: "Kiran Cloud Services, Pune", confidence: 0.92 },
      { field: "job_2_dates", label: "Job 2 dates", value: "Jun 2023 - Dec 2023", confidence: 0.97 },
      { field: "project_1_name", label: "Project 1 name", value: "LedgerLite - Double-entry Bookkeeping API", confidence: 0.99 },
      { field: "project_1_tech", label: "Project 1 tech", value: "Go, PostgreSQL", confidence: 0.97 },
      { field: "education_1_degree", label: "Education 1 degree", value: "BE in Computer Engineering", confidence: 0.98 },
      { field: "education_1_school", label: "Education 1 school", value: "Savitribai Phule Pune University", confidence: 0.99 },
      { field: "education_1_years", label: "Education 1 years", value: "2019 - 2023", confidence: 0.96 },
      { field: "skills_languages", label: "Skills: Languages", value: "Go, Python, SQL, TypeScript", confidence: 0.98 },
      { field: "skills_tools", label: "Skills: Tools", value: "PostgreSQL, Redis, Docker, Kubernetes, GitHub Actions, Grafana", confidence: 0.96 },
    ],
  },
  {
    id: "receipt",
    label: "Receipt",
    text: "KRISHNA STORES\nReceipt #KS-1141\nDate: 12/09/2026 18:42\n2 Amul Milk 500ml @ 27.00   54.00\n1 Britannia Bread   45.00\n1 Tata Salt 1kg   28.00\nSubtotal   127.00\nTotal   127.00\nCash   150.00\nChange   23.00",
    extracted: [
      { field: "merchant", label: "Merchant", value: "Krishna Stores", confidence: 0.98 },
      { field: "total", label: "Total", value: "127.00", confidence: 0.97 },
      { field: "change", label: "Change", value: "32.00", confidence: 0.9 },
      { field: "date", label: "Date", value: "12/09/2026", confidence: 0.95 },
    ],
  },
  {
    id: "statement",
    label: "Bank statement",
    text: "LAKEVIEW BANK\nAccount Statement as of 30 Sep 2026\nAccount Holder    MEERA NAIR\nAccount Number    50200123456\nIFSC Code    LAKE0001234\nPeriod    01 Sep 2026 to 30 Sep 2026\nOpening Balance    12,500.00\nClosing Balance    9,804.00\n01/09/2026 UPI-RAJU TEA STALL DR 40.00 12,460.00\n03/09/2026 SALARY CREDIT CR 45,000.00 57,460.00\n10/09/2026 ELECTRICITY BOARD DR 1,820.00 55,640.00\n28/09/2026 RENT TRANSFER DR 18,000.00 37,640.00\n30/09/2026 ATM CASH WITHDRAWAL DR 27,836.00 9,804.00",
    extracted: [
      { field: "bank_name", label: "Bank", value: "Lakeview Bank", confidence: 0.99 },
      { field: "account_number", label: "Account number", value: "50200123456", confidence: 0.97 },
      { field: "closing_balance", label: "Closing balance", value: "9,804.00", confidence: 0.96 },
      { field: "opening_balance", label: "Opening balance", value: "12,500", confidence: 0.93 },
    ],
  },
  {
    id: "form",
    label: "Form",
    text: "LEAVE APPLICATION FORM\nNAME:   Meera Nair\nDEPARTMENT:   Accounts\nFROM DATE:   05/10/2026   TO DATE:   09/10/2026\nREASON:   Family function\nCONTACT NUMBER:   98450 12345\nSIGNATURE:\nAPPROVED BY:",
    extracted: [
      { field: "name", label: "Name", value: "Meera Nair", confidence: 0.98 },
      { field: "department", label: "Department", value: "Accounts", confidence: 0.97 },
      { field: "from_date", label: "From date", value: "05/10/2026", confidence: 0.96 },
      { field: "reason", label: "Reason", value: "Family function", confidence: 0.9 },
    ],
  },
  {
    id: "longreceipt",
    label: "Long receipt (10 items)",
    text: "ANNA SUPER MARKET\nNo. 5521\n12/09/2026 19:05\n2 Rice 5kg @ 310.00   620.00\n1 Toor Dal 1kg   145.00\n1 Sunflower Oil 1L   132.00\n3 Parle-G Gold @ 10.00   30.00\n1\nDetergent Bar   85.00\n2 Curd Cup 400g @ 35.00   70.00\n1 Wheat Flour 5kg   240.00\n1 Sugar 1kg   45.00\n4 Milk 500ml @ 27.00   108.00\n1 Tea Powder 250g   140.00\nFOOD   1,530.00\nHOUSEHOLD   85.00\nSubtotal   1,615.00\nDiscount   115.00\nTotal\n1,500.00\nCash   2,000.00\nChange   500.00",
    extracted: [
      { field: "merchant", label: "Merchant", value: "Anna Super Market", confidence: 0.98 },
      { field: "date", label: "Date", value: "12/09/2026", confidence: 0.98 },
      { field: "item_1_name", label: "Item 1 name", value: "Rice 5kg", confidence: 0.98 },
      { field: "item_1_qty", label: "Item 1 quantity", value: "2", confidence: 0.97 },
      { field: "item_1_unit_price", label: "Item 1 unit price", value: "310.00", confidence: 0.96 },
      { field: "item_1_price", label: "Item 1 price", value: "620.00", confidence: 0.98 },
      { field: "item_2_name", label: "Item 2 name", value: "Toor Dal 1kg", confidence: 0.98 },
      { field: "item_2_qty", label: "Item 2 quantity", value: "1", confidence: 0.97 },
      { field: "item_2_price", label: "Item 2 price", value: "145.00", confidence: 0.98 },
      { field: "item_3_name", label: "Item 3 name", value: "Sunflower Oil 1L", confidence: 0.98 },
      { field: "item_3_qty", label: "Item 3 quantity", value: "1", confidence: 0.97 },
      { field: "item_3_price", label: "Item 3 price", value: "132.00", confidence: 0.98 },
      { field: "item_4_name", label: "Item 4 name", value: "Parle-G Gold", confidence: 0.98 },
      { field: "item_4_qty", label: "Item 4 quantity", value: "3", confidence: 0.97 },
      { field: "item_4_unit_price", label: "Item 4 unit price", value: "10.00", confidence: 0.96 },
      { field: "item_4_price", label: "Item 4 price", value: "30.00", confidence: 0.98 },
      { field: "item_5_name", label: "Item 5 name", value: "Detergent Bar", confidence: 0.98 },
      { field: "item_5_price", label: "Item 5 price", value: "85.00", confidence: 0.98 },
      { field: "item_6_name", label: "Item 6 name", value: "Curd Cup 400g", confidence: 0.98 },
      { field: "item_6_qty", label: "Item 6 quantity", value: "2", confidence: 0.97 },
      { field: "item_6_unit_price", label: "Item 6 unit price", value: "35.00", confidence: 0.96 },
      { field: "item_6_price", label: "Item 6 price", value: "70.00", confidence: 0.98 },
      { field: "item_7_name", label: "Item 7 name", value: "Wheat Flour 5kg", confidence: 0.98 },
      { field: "item_7_qty", label: "Item 7 quantity", value: "1", confidence: 0.97 },
      { field: "item_7_price", label: "Item 7 price", value: "240.00", confidence: 0.98 },
      { field: "item_8_name", label: "Item 8 name", value: "Sugar 1kg", confidence: 0.98 },
      { field: "item_8_qty", label: "Item 8 quantity", value: "1", confidence: 0.97 },
      { field: "item_8_price", label: "Item 8 price", value: "45.00", confidence: 0.98 },
      { field: "item_9_name", label: "Item 9 name", value: "Milk 500ml", confidence: 0.98 },
      { field: "item_9_qty", label: "Item 9 quantity", value: "4", confidence: 0.97 },
      { field: "item_9_unit_price", label: "Item 9 unit price", value: "27.00", confidence: 0.96 },
      { field: "item_9_price", label: "Item 9 price", value: "108.00", confidence: 0.98 },
      { field: "item_10_name", label: "Item 10 name", value: "Tea Powder 250g", confidence: 0.98 },
      { field: "item_10_qty", label: "Item 10 quantity", value: "1", confidence: 0.97 },
      { field: "item_10_price", label: "Item 10 price", value: "140.00", confidence: 0.98 },
      { field: "item_5_qty", label: "Item 5 quantity", value: null, confidence: 0.5 },
      { field: "no", label: "Bill number", value: "5521", confidence: 0.9 },
      { field: "food", label: "Food", value: "1,530.00", confidence: 0.97 },
      { field: "household", label: "Household", value: "85.00", confidence: 0.97 },
      { field: "subtotal", label: "Subtotal", value: "1,615.00", confidence: 0.98 },
      { field: "discount", label: "Discount", value: "115.00", confidence: 0.93 },
      { field: "total", label: "Total", value: "1,500.00", confidence: 0.98 },
      { field: "cash", label: "Cash", value: "2,000.00", confidence: 0.98 },
      { field: "change", label: "Change", value: "500.00", confidence: 0.97 },
    ],
  },
];

export const DEFAULT_FIELDS = [
  { name: "vendor_name", label: "Vendor", description: "company that sent the invoice" },
  { name: "invoice_number", label: "Invoice number", description: "the invoice id" },
  { name: "due_date", label: "Due date", description: "payment due date as YYYY-MM-DD", type: "date" },
  { name: "total_amount", label: "Total amount", description: "final amount payable, number only", type: "number" },
];
